name: Feature Request
description: Submit a feature request
title: "[Feature]: "
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Please read [this](https://engineering.hmn.md/projects/support/) before proceeding forward.
        
        Please note that we don't offer detailed end-user support.

        This template is just for feature requests, not for questions.
        
        If the opened issue doesn't have all of the needed information, or it's off-topic, we will close it.
        
        Please provide as much details as possible about the feature you need.
        
        Thank you for helping us build a better product.

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Is this request related to a specific problem, workflow, or limitation?
      placeholder: Describe the background or scenario that led to this request.
    validations:
      required: true

  - type: textarea
    id: current_behaviour
    attributes:
      label: Current Behaviour
      description: A precise description of how things work now
      placeholder: How is it working now?
    validations:
      required: true
      
  - type: textarea
    id: improved_behaviour
    attributes:
      label: Improved Behaviour
      description: A precise description of how things should work
      placeholder: How it should be working?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: An explanation why you believe this brings value and what's the impact on other users
      placeholder: |
        What's the value?
        What's the impact?
    validations:
      required: true

  - type: textarea
    id: possible_solutions
    attributes:
      label: Possible Solutions
      description: Do you already have ideas or examples of how this could be implemented?
      placeholder: Share your thoughts, examples, or references.
    validations:
      required: false
      
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: When would you say this feature is complete? List clear conditions or test cases.
      placeholder: |
        - [ ] User can do X
        - [ ] Feature works under Y condition
        - [ ] Documentation updated
    validations:
      required: false
